# Generated by Django 5.1.4 on 2025-01-23 05:14

import cloudinary.models
import datetime
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mr"),
                            ("mrs", "Mrs"),
                            ("miss", "Miss"),
                            ("master", "Master"),
                        ],
                        default="master",
                        max_length=8,
                        verbose_name="Salutation",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        max_length=8,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        default=datetime.date(2005, 1, 1), verbose_name="Date of Birth"
                    ),
                ),
                (
                    "country_of_birth",
                    django_countries.fields.CountryField(
                        default="IN", max_length=2, verbose_name="Country of Birth"
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        default="Unknown", max_length=55, verbose_name="Place of Birth"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "means_of_identification",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("drivers_license", "Drivers License"),
                            ("voters_card", "Voters Card"),
                            (
                                "national_health_insurance_card",
                                "National Health Insurance Card",
                            ),
                        ],
                        default="national_id",
                        max_length=35,
                        verbose_name="Means of Identification",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Identification Number",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Unknown", max_length=35, verbose_name="Nationality"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="+91 0000000000",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="Unknown",
                        max_length=55,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        default="Unknown",
                        max_length=55,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("self_employed", "Self-Employed"),
                            ("retired", "Retired"),
                            ("student", "Student"),
                            ("housewife", "Housewife"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=55, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "date_of_employment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Employment"
                    ),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Photo"
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(blank=True, null=True, verbose_name="Photo URL"),
                ),
                (
                    "id_photo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="ID Photo"
                    ),
                ),
                (
                    "id_photo_url",
                    models.URLField(blank=True, null=True, verbose_name="ID Photo URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
            },
        ),
    ]
